name: Auto Tag with Date

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Needed to push tags

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Tag with today's date
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="v$(date +'%Y.%m.%d')"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag -a "$VERSION" -m "Auto tag on push"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} "$VERSION"
