name: Auto Tag with Date

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Tag with today's date
        run: |
          VERSION="v$(date +'%Y.%m.%d')"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag -a "$VERSION" -m "Auto tag on push"
          git push origin "$VERSION"
